unique_ids:
  assets:
    standard-page.html: UJSHLBOCNJECACUVXLYLKXNO737M7SDY
    theme.css: HX26RMO26XZWJIWQUZTQSMATSNX35HXO
  forms:
    Form1: 6ZLBBWQTOK3EMG7DP72Y7P3NDR5QVE22
  modules: {}
  scripts: {}
  server_modules: {}
